<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

class Encuesta extends REST_Controller
{	
	/**
	 * GET
	 */
	public function data_get()
	{
		
	}
	
	/**
	 * POST
	 */
	public function data_post()
	{
		// Create a new item
		$response = array();
		$p1 = $this->post('p1');
		$p2 = $this->post('p2');
		$p3 = $this->post('p3');
		$p4 = $this->post('p4');
		$p5 = $this->post('p5');

		if (!empty($p1) && !empty($p5)) {
			$data['p1'] = $p1;
			$data['p2'] = $p2;
			$data['p3'] = $p3;
			$data['p4'] = $p4;
			$data['p5'] = $p5;
		  
			$this->load->database();
			$this->db->insert('ac_encuestas', $data);
			$id = $this->db->insert_id();

			$response = [
				'status' => true,
				'id' => $id, // Automatically generated by the model
			];		
			$this->set_response($response, REST_Controller::HTTP_CREATED);
		} else {
		  $this->set_response([
			  'status' => FALSE,
			  'message' => 'No users were found'
		  ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
		}
	}
  
}